name = "proj6"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Proj6", "lib"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.26.0-rc2"

# This builds the files in your main folder
[[lean_lib]]
name = "Proj6"
roots = ["basechange"]

# This builds the files inside the lib folder
[[lean_lib]]
name = "lib"
roots = [
  "lib.Basic", 
  "lib.dirlimitchange", 
  "lib.Domination", 
  "lib.fpLemma", 
  "lib.Kap", 
  "lib.Lazard", 
  "lib.mlModule", 
  "lib.mlSystem", 
  "lib.Pushout", 
  "lib.UnivInj"
]
