name = "proj6"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["lib"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.26.0-rc2"

[[lean_lib]]
name = "lib"
roots = ["lib.Kap", "lib.mlModule", "lib.mlSystem", "lib.Lazard", "lib.Pushout", "lib.UnivInj", "lib.Domination", "lib.dirlimitchange", "lib.fpLemma"]
